#image: ruby:2.4.2

stages:
#  - build
#  - test
#  - review
  - stage
#  - production


staging:
 stage: stage
# when: manual
# only:
#   - /^\d+\.\d+\.\d+/
   
 before_script:
   - if [ -z "$env_folder" ]; then echo "Need to set env_folder" && exit 1; fi

 script:
    - echo 'Deploy'
    - rsync -r ./ $env_folder --exclude '.git' --exclude '.gitlab-ci.yml' --exclude '.gitignore' --delete 
    - cd $env_folder/src
    - docker-compose up -d --build

 environment:
    name: stage
    url: https://beta.example.com





